import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ["DM Sans", "Google Sans", "system-ui", "-apple-system", "sans-serif"],
        tight:   ["DM Sans", "Google Sans", "system-ui", "sans-serif"],
        mono:    ["JetBrains Mono", "Fira Code", "Consolas", "monospace"],
        display: ["DM Sans", "Google Sans", "system-ui", "sans-serif"],
      },
      colors: {
        bg: {
          base:    "var(--bg)",
          surface: "var(--surface)",
          elevated:"var(--surface-2)",
          overlay: "var(--surface-3)",
          panel:   "var(--surface)",
        },
        border: {
          DEFAULT: "var(--border)",
          subtle:  "var(--border)",
          strong:  "var(--border-strong)",
          accent:  "var(--accent-border)",
        },
        primary: {
          DEFAULT: "var(--accent)",
          hover:   "var(--accent-hover)",
          dim:     "var(--accent-dim)",
          muted:   "var(--accent)",
          dark:    "var(--accent-dark)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover:   "var(--accent-hover)",
          dim:     "var(--accent-dim)",
          dark:    "var(--accent-dark)",
        },
        success: {
          DEFAULT: "var(--green)",
          hover:   "var(--green-hover)",
          dim:     "var(--green-dim)",
          dark:    "var(--green-dark)",
        },
        danger: {
          DEFAULT: "var(--red)",
          hover:   "var(--red)",
          dim:     "var(--red-dim)",
        },
        warning: {
          DEFAULT: "var(--amber)",
          hover:   "var(--amber)",
          dim:     "var(--amber-dim)",
        },
        text: {
          primary:   "var(--text-1)",
          secondary: "var(--text-2)",
          muted:     "var(--text-3)",
          dim:       "var(--text-4)",
          inverse:   "#FFFFFF",
          accent:    "var(--accent)",
          link:      "var(--accent)",
        },
      },
      fontSize: {
        "2xs": ["10px", "14px"],
        "xs":  ["11px", "16px"],
        "sm":  ["12px", "18px"],
        "base":["13px", "20px"],
        "md":  ["14px", "22px"],
        "lg":  ["16px", "24px"],
        "xl":  ["18px", "26px"],
        "2xl": ["22px", "30px"],
        "3xl": ["28px", "36px"],
        "4xl": ["36px", "44px"],
        "5xl": ["48px", "54px"],
        "6xl": ["64px", "70px"],
      },
      borderRadius: {
        none:    "0",
        sm:      "4px",
        DEFAULT: "8px",
        md:      "8px",
        lg:      "12px",
        xl:      "16px",
        "2xl":   "20px",
        full:    "9999px",
      },
      animation: {
        "fade-in":   "fadeIn 0.2s ease-out",
        "slide-up":  "slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-in":  "slideIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
        "shimmer":   "shimmer 1.8s infinite ease-in-out",
        "pulse-dot": "pulseDot 2s ease-in-out infinite",
        "spin":      "spin 1s linear infinite",
        "bounce-in": "bounceIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1)",
        "marquee":   "marquee 40s linear infinite",
      },
      keyframes: {
        fadeIn:   { from: { opacity: "0" }, to: { opacity: "1" } },
        slideUp:  { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideIn:  { from: { opacity: "0", transform: "translateX(-16px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        shimmer:  { "0%": { backgroundPosition: "100% 0" }, "100%": { backgroundPosition: "-100% 0" } },
        pulseDot: { "0%,100%": { opacity: "1", transform: "scale(1)" }, "50%": { opacity: "0.4", transform: "scale(0.75)" } },
        spin:     { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        bounceIn: { from: { opacity: "0", transform: "scale(0.85)" }, to: { opacity: "1", transform: "scale(1)" } },
        marquee:  { "0%": { transform: "translateX(0)" }, "100%": { transform: "translateX(-50%)" } },
      },
      boxShadow: {
        card:        "0 1px 3px rgba(0,0,0,0.06), 0 0 0 1px rgba(33,34,38,0.06)",
        "card-hover":"0 4px 16px rgba(0,0,0,0.08), 0 0 0 1px rgba(33,34,38,0.08)",
        accent:      "0 4px 20px rgba(50,121,249,0.22)",
        yellow:      "0 4px 16px rgba(50,121,249,0.15)",
        green:       "0 4px 16px rgba(39,174,96,0.18)",
        inset:       "inset 0 1px 3px rgba(0,0,0,0.06)",
        btn:         "0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.05)",
        "btn-hover": "0 4px 12px rgba(0,0,0,0.12)",
      },
    },
  },
  plugins: [],
} satisfies Config;
