export interface NseStock {
  symbol: string;
  name: string;
  sector: string;
}

export const NSE_STOCKS: NseStock[] = [
  // NIFTY 50
  { symbol: "RELIANCE", name: "Reliance Industries", sector: "Energy" },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "IT" },
  { symbol: "HDFCBANK", name: "HDFC Bank", sector: "Banking" },
  { symbol: "INFY", name: "Infosys", sector: "IT" },
  { symbol: "ICICIBANK", name: "ICICI Bank", sector: "Banking" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever", sector: "FMCG" },
  { symbol: "ITC", name: "ITC Limited", sector: "FMCG" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel", sector: "Telecom" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Banking" },
  { symbol: "LT", name: "Larsen & Toubro", sector: "Industrials" },
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Materials" },
  { symbol: "AXISBANK", name: "Axis Bank", sector: "Banking" },
  { symbol: "MARUTI", name: "Maruti Suzuki India", sector: "Auto" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical", sector: "Healthcare" },
  { symbol: "TATAMOTORS", name: "Tata Motors", sector: "Auto" },
  { symbol: "WIPRO", name: "Wipro", sector: "IT" },
  { symbol: "NESTLEIND", name: "Nestle India", sector: "FMCG" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement", sector: "Materials" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "Finance" },
  { symbol: "HCLTECH", name: "HCL Technologies", sector: "IT" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Utilities" },
  { symbol: "NTPC", name: "NTPC Limited", sector: "Utilities" },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Finance" },
  { symbol: "M&M", name: "Mahindra & Mahindra", sector: "Auto" },
  { symbol: "ADANIENT", name: "Adani Enterprises", sector: "Industrials" },
  { symbol: "JSWSTEEL", name: "JSW Steel", sector: "Metals" },
  { symbol: "TATASTEEL", name: "Tata Steel", sector: "Metals" },
  { symbol: "TECHM", name: "Tech Mahindra", sector: "IT" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank", sector: "Banking" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Energy" },
  { symbol: "COALINDIA", name: "Coal India", sector: "Energy" },
  { symbol: "BPCL", name: "Bharat Petroleum", sector: "Energy" },
  { symbol: "GRASIM", name: "Grasim Industries", sector: "Materials" },
  { symbol: "HINDALCO", name: "Hindalco Industries", sector: "Metals" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories", sector: "Healthcare" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", sector: "Healthcare" },
  { symbol: "CIPLA", name: "Cipla", sector: "Healthcare" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals", sector: "Healthcare" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", sector: "FMCG" },
  { symbol: "BRITANNIA", name: "Britannia Industries", sector: "FMCG" },
  { symbol: "EICHERMOT", name: "Eicher Motors", sector: "Auto" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp", sector: "Auto" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto", sector: "Auto" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Industrials" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", sector: "Finance" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", sector: "Finance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", sector: "Finance" },
  // Nifty Next 50
  { symbol: "ADANIGREEN", name: "Adani Green Energy", sector: "Utilities" },
  { symbol: "ADANIPOWER", name: "Adani Power", sector: "Utilities" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements", sector: "Materials" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma", sector: "Healthcare" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank", sector: "Banking" },
  { symbol: "BERGEPAINT", name: "Berger Paints India", sector: "Materials" },
  { symbol: "BEL", name: "Bharat Electronics", sector: "Defence" },
  { symbol: "BIOCON", name: "Biocon", sector: "Healthcare" },
  { symbol: "BOSCHLTD", name: "Bosch", sector: "Auto" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", sector: "Finance" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India", sector: "FMCG" },
  { symbol: "CONCOR", name: "Container Corporation", sector: "Logistics" },
  { symbol: "DABUR", name: "Dabur India", sector: "FMCG" },
  { symbol: "DLF", name: "DLF", sector: "Real Estate" },
  { symbol: "ESCORTS", name: "Escorts Kubota", sector: "Auto" },
  { symbol: "FEDERALBNK", name: "Federal Bank", sector: "Banking" },
  { symbol: "GAIL", name: "GAIL (India)", sector: "Energy" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", sector: "FMCG" },
  { symbol: "GODREJPROP", name: "Godrej Properties", sector: "Real Estate" },
  { symbol: "HAVELLS", name: "Havells India", sector: "Consumer" },
  { symbol: "HAL", name: "Hindustan Aeronautics", sector: "Defence" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank", sector: "Banking" },
  { symbol: "INDHOTEL", name: "Indian Hotels", sector: "Consumer" },
  { symbol: "IOC", name: "Indian Oil Corporation", sector: "Energy" },
  { symbol: "IRCTC", name: "Indian Railway Catering", sector: "Consumer" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", sector: "Metals" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks", sector: "Consumer" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints", sector: "Materials" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "Finance" },
  { symbol: "LUPIN", name: "Lupin", sector: "Healthcare" },
  { symbol: "MARICO", name: "Marico", sector: "FMCG" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson", sector: "Auto" },
  { symbol: "MPHASIS", name: "Mphasis", sector: "IT" },
  { symbol: "MRF", name: "MRF", sector: "Auto" },
  { symbol: "NAUKRI", name: "Info Edge India", sector: "IT" },
  { symbol: "NMDC", name: "NMDC", sector: "Metals" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", sector: "Real Estate" },
  { symbol: "OFSS", name: "Oracle Financial Services", sector: "IT" },
  { symbol: "PAGEIND", name: "Page Industries", sector: "Consumer" },
  { symbol: "PERSISTENT", name: "Persistent Systems", sector: "IT" },
  { symbol: "PETRONET", name: "Petronet LNG", sector: "Energy" },
  { symbol: "PIIND", name: "PI Industries", sector: "Chemicals" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", sector: "Chemicals" },
  { symbol: "POLYCAB", name: "Polycab India", sector: "Consumer" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene", sector: "FMCG" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking" },
  { symbol: "SBICARD", name: "SBI Cards & Payment", sector: "Finance" },
  { symbol: "SHREECEM", name: "Shree Cement", sector: "Materials" },
  { symbol: "SIEMENS", name: "Siemens India", sector: "Industrials" },
  { symbol: "SRF", name: "SRF", sector: "Chemicals" },
  { symbol: "TATACOMM", name: "Tata Communications", sector: "Telecom" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", sector: "IT" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", sector: "Healthcare" },
  { symbol: "TORNTPOWER", name: "Torrent Power", sector: "Utilities" },
  { symbol: "TRENT", name: "Trent", sector: "Consumer" },
  { symbol: "UBL", name: "United Breweries", sector: "Consumer" },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking" },
  { symbol: "UPL", name: "UPL", sector: "Chemicals" },
  { symbol: "VEDL", name: "Vedanta", sector: "Metals" },
  { symbol: "VOLTAS", name: "Voltas", sector: "Consumer" },
  { symbol: "ZOMATO", name: "Zomato", sector: "Consumer" },
  { symbol: "PAYTM", name: "One 97 Communications", sector: "Finance" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", sector: "Consumer" },
  { symbol: "DELHIVERY", name: "Delhivery", sector: "Logistics" },
  { symbol: "POLICYBZR", name: "PB Fintech", sector: "Finance" },
  // IT & Tech
  { symbol: "COFORGE", name: "Coforge", sector: "IT" },
  { symbol: "HEXAWARE", name: "Hexaware Technologies", sector: "IT" },
  { symbol: "LTIM", name: "LTIMindtree", sector: "IT" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "IT" },
  { symbol: "KPITTECH", name: "KPIT Technologies", sector: "IT" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT" },
  { symbol: "TANLA", name: "Tanla Platforms", sector: "IT" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", sector: "IT" },
  { symbol: "MASTEK", name: "Mastek", sector: "IT" },
  { symbol: "ROUTE", name: "Route Mobile", sector: "IT" },
  { symbol: "NAZARA", name: "Nazara Technologies", sector: "IT" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", sector: "IT" },
  { symbol: "JUSTDIAL", name: "Just Dial", sector: "IT" },
  { symbol: "TATATECH", name: "Tata Technologies", sector: "IT" },
  { symbol: "INTELLECT", name: "Intellect Design Arena", sector: "IT" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies", sector: "IT" },
  { symbol: "CYIENT", name: "Cyient", sector: "IT" },
  { symbol: "NIITTECH", name: "NIIT Technologies", sector: "IT" },
  { symbol: "SONATSOFTW", name: "Sonata Software", sector: "IT" },
  { symbol: "ZENSAR", name: "Zensar Technologies", sector: "IT" },
  { symbol: "BIRLASOFT", name: "Birlasoft", sector: "IT" },
  { symbol: "MINDTREE", name: "Mindtree", sector: "IT" },
  { symbol: "ECLERX", name: "eClerx Services", sector: "IT" },
  { symbol: "INFOSONSE", name: "Infosys BPM", sector: "IT" },
  { symbol: "EXPERIAN", name: "Experian Credit Information", sector: "IT" },
  { symbol: "FSL", name: "Firstsource Solutions", sector: "IT" },
  { symbol: "WIPRO", name: "Wipro", sector: "IT" },
  { symbol: "MPHASIS", name: "Mphasis", sector: "IT" },
  { symbol: "KFINTECH", name: "KFin Technologies", sector: "Finance" },
  { symbol: "CAMS", name: "Computer Age Management Services", sector: "Finance" },
  { symbol: "CDSL", name: "Central Depository Services", sector: "Finance" },
  { symbol: "BSE", name: "BSE Limited", sector: "Finance" },
  { symbol: "MCX", name: "Multi Commodity Exchange", sector: "Finance" },
  // Banking
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking" },
  { symbol: "BANKINDIA", name: "Bank of India", sector: "Banking" },
  { symbol: "BANKOFMAHARASHTRA", name: "Bank of Maharashtra", sector: "Banking" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra", sector: "Banking" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking" },
  { symbol: "KARURVYSYA", name: "Karur Vysya Bank", sector: "Banking" },
  { symbol: "DCBBANK", name: "DCB Bank", sector: "Banking" },
  { symbol: "CSBBANK", name: "CSB Bank", sector: "Banking" },
  { symbol: "RBLBANK", name: "RBL Bank", sector: "Banking" },
  { symbol: "UJJIVANSFB", name: "Ujjivan Small Finance Bank", sector: "Banking" },
  { symbol: "AUBANK", name: "AU Small Finance Bank", sector: "Banking" },
  { symbol: "EQUITASBNK", name: "Equitas Small Finance Bank", sector: "Banking" },
  { symbol: "ESAFSFB", name: "ESAF Small Finance Bank", sector: "Banking" },
  { symbol: "SURYODAY", name: "Suryoday Small Finance Bank", sector: "Banking" },
  { symbol: "JAIBALAJI", name: "Jai Balaji Industries", sector: "Metals" },
  { symbol: "SOUTHBANK", name: "South Indian Bank", sector: "Banking" },
  { symbol: "LAKSHVILAS", name: "Lakshmi Vilas Bank", sector: "Banking" },
  { symbol: "CUB", name: "City Union Bank", sector: "Banking" },
  { symbol: "TMBBANK", name: "Tamilnad Mercantile Bank", sector: "Banking" },
  { symbol: "JKBANK", name: "J&K Bank", sector: "Banking" },
  { symbol: "NAINITALBANK", name: "Nainital Bank", sector: "Banking" },
  { symbol: "SARASWATBANK", name: "Saraswat Bank", sector: "Banking" },
  // Finance / NBFC
  { symbol: "BAJAJHFL", name: "Bajaj Housing Finance", sector: "Finance" },
  { symbol: "CANFINHOME", name: "Can Fin Homes", sector: "Finance" },
  { symbol: "HOMEFIRST", name: "Home First Finance Company", sector: "Finance" },
  { symbol: "APTUS", name: "Aptus Value Housing Finance", sector: "Finance" },
  { symbol: "AAVAS", name: "Aavas Financiers", sector: "Finance" },
  { symbol: "IIFL", name: "IIFL Finance", sector: "Finance" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance", sector: "Finance" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", sector: "Finance" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", sector: "Finance" },
  { symbol: "PNBHOUSING", name: "PNB Housing Finance", sector: "Finance" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "Finance" },
  { symbol: "REPCO", name: "Repco Home Finance", sector: "Finance" },
  { symbol: "GRUH", name: "GRUH Finance", sector: "Finance" },
  { symbol: "SUNDARMFIN", name: "Sundaram Finance", sector: "Finance" },
  { symbol: "MAHINDCIE", name: "Mahindra CIE Automotive", sector: "Auto" },
  { symbol: "CRISIL", name: "CRISIL", sector: "Finance" },
  { symbol: "IRFC", name: "Indian Railway Finance", sector: "Finance" },
  { symbol: "REC", name: "REC Limited", sector: "Finance" },
  { symbol: "PFC", name: "Power Finance Corporation", sector: "Finance" },
  { symbol: "HUDCO", name: "Housing & Urban Development", sector: "Finance" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation", sector: "Finance" },
  { symbol: "MFSL", name: "Max Financial Services", sector: "Finance" },
  { symbol: "UTIAMC", name: "UTI Asset Management", sector: "Finance" },
  { symbol: "HDFCAMC", name: "HDFC Asset Management", sector: "Finance" },
  { symbol: "NIPPONLIFE", name: "Nippon Life India AMC", sector: "Finance" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC", sector: "Finance" },
  { symbol: "360ONE", name: "360 One WAM", sector: "Finance" },
  { symbol: "MOTILALOFS", name: "Motilal Oswal Financial Services", sector: "Finance" },
  { symbol: "ANGELONE", name: "Angel One", sector: "Finance" },
  { symbol: "IIFLSEC", name: "IIFL Securities", sector: "Finance" },
  { symbol: "SMCGLOBAL", name: "SMC Global Securities", sector: "Finance" },
  { symbol: "SPANDANA", name: "Spandana Sphoorty Financial", sector: "Finance" },
  { symbol: "CREDITACC", name: "CreditAccess Grameen", sector: "Finance" },
  { symbol: "ARMAN", name: "Arman Financial Services", sector: "Finance" },
  { symbol: "VARTHANA", name: "Varthana Finance", sector: "Finance" },
  { symbol: "UGROCAP", name: "Ugro Capital", sector: "Finance" },
  { symbol: "SATIN", name: "Satin Creditcare Network", sector: "Finance" },
  // Insurance
  { symbol: "GICRE", name: "General Insurance Corporation", sector: "Finance" },
  { symbol: "NIACL", name: "New India Assurance", sector: "Finance" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", sector: "Finance" },
  { symbol: "STARHEALTH", name: "Star Health Insurance", sector: "Finance" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life", sector: "Finance" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", sector: "Healthcare" },
  // Auto & EV
  { symbol: "TVSMOTOR", name: "TVS Motor Company", sector: "Auto" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland", sector: "Auto" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", sector: "Auto" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries", sector: "Auto" },
  { symbol: "CEATLTD", name: "CEAT", sector: "Auto" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India", sector: "Auto" },
  { symbol: "BOSCHLTD", name: "Bosch", sector: "Auto" },
  { symbol: "WABCOINDIA", name: "WABCO India", sector: "Auto" },
  { symbol: "SUNDRMFAST", name: "Sundram Fasteners", sector: "Auto" },
  { symbol: "EXIDEIND", name: "Exide Industries", sector: "Auto" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy", sector: "Auto" },
  { symbol: "ENDURANCE", name: "Endurance Technologies", sector: "Auto" },
  { symbol: "SUPRAJIT", name: "Suprajit Engineering", sector: "Auto" },
  { symbol: "Gabriel", name: "Gabriel India", sector: "Auto" },
  { symbol: "FIEM", name: "FIEM Industries", sector: "Auto" },
  { symbol: "MINDA", name: "Minda Corporation", sector: "Auto" },
  { symbol: "MINDAIND", name: "Minda Industries", sector: "Auto" },
  { symbol: "TIINDIA", name: "Tube Investments of India", sector: "Auto" },
  { symbol: "CRAFTSMAN", name: "Craftsman Automation", sector: "Auto" },
  { symbol: "OLECTRA", name: "Olectra Greentech", sector: "Auto" },
  { symbol: "EVVOL", name: "EV Voltz Industries", sector: "Auto" },
  // Healthcare & Pharma
  { symbol: "ALKEM", name: "Alkem Laboratories", sector: "Healthcare" },
  { symbol: "GRANULES", name: "Granules India", sector: "Healthcare" },
  { symbol: "GLAND", name: "Gland Pharma", sector: "Healthcare" },
  { symbol: "LAURUSLABS", name: "Laurus Labs", sector: "Healthcare" },
  { symbol: "IPCALAB", name: "IPCA Laboratories", sector: "Healthcare" },
  { symbol: "NATCOPHARM", name: "Natco Pharma", sector: "Healthcare" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", sector: "Healthcare" },
  { symbol: "PFIZER", name: "Pfizer", sector: "Healthcare" },
  { symbol: "SANOFI", name: "Sanofi India", sector: "Healthcare" },
  { symbol: "ABBOTINDIA", name: "Abbott India", sector: "Healthcare" },
  { symbol: "GLAXO", name: "GlaxoSmithKline Pharmaceuticals", sector: "Healthcare" },
  { symbol: "ASTRAZEN", name: "AstraZeneca Pharma India", sector: "Healthcare" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare", sector: "Healthcare" },
  { symbol: "LALPATHLAB", name: "Dr Lal PathLabs", sector: "Healthcare" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies", sector: "Healthcare" },
  { symbol: "KRSNAA", name: "Krsnaa Diagnostics", sector: "Healthcare" },
  { symbol: "VIJAYA", name: "Vijaya Diagnostic Centre", sector: "Healthcare" },
  { symbol: "SUVENPHAR", name: "Suven Pharmaceuticals", sector: "Healthcare" },
  { symbol: "SYNGENE", name: "Syngene International", sector: "Healthcare" },
  { symbol: "MEDANTA", name: "Global Health (Medanta)", sector: "Healthcare" },
  { symbol: "ASTER", name: "Aster DM Healthcare", sector: "Healthcare" },
  { symbol: "NARAYANA", name: "Narayana Hrudayalaya", sector: "Healthcare" },
  { symbol: "NH", name: "Narayana Hrudayalaya", sector: "Healthcare" },
  { symbol: "FORTIS", name: "Fortis Healthcare", sector: "Healthcare" },
  { symbol: "HCG", name: "Healthcare Global Enterprises", sector: "Healthcare" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical Industries", sector: "Chemicals" },
  { symbol: "CADILAHC", name: "Cadila Healthcare (Zydus)", sector: "Healthcare" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences", sector: "Healthcare" },
  { symbol: "ERIS", name: "Eris Lifesciences", sector: "Healthcare" },
  { symbol: "JB", name: "JB Chemicals & Pharmaceuticals", sector: "Healthcare" },
  { symbol: "SHILPAMED", name: "Shilpa Medicare", sector: "Healthcare" },
  { symbol: "MOREPEN", name: "Morepen Laboratories", sector: "Healthcare" },
  { symbol: "STERLINBIO", name: "Sterling Biotech", sector: "Healthcare" },
  // Chemicals
  { symbol: "AARTIIND", name: "Aarti Industries", sector: "Chemicals" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals", sector: "Chemicals" },
  { symbol: "GALAXYSURF", name: "Galaxy Surfactants", sector: "Chemicals" },
  { symbol: "VINATI", name: "Vinati Organics", sector: "Chemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite", sector: "Chemicals" },
  { symbol: "CLEAN", name: "Clean Science Technology", sector: "Chemicals" },
  { symbol: "FINEORG", name: "Fine Organic Industries", sector: "Chemicals" },
  { symbol: "PIIND", name: "PI Industries", sector: "Chemicals" },
  { symbol: "SRF", name: "SRF", sector: "Chemicals" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals", sector: "Chemicals" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International", sector: "Chemicals" },
  { symbol: "TATACHEM", name: "Tata Chemicals", sector: "Chemicals" },
  { symbol: "UPL", name: "UPL", sector: "Chemicals" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers", sector: "Chemicals" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fert", sector: "Chemicals" },
  { symbol: "ATUL", name: "Atul", sector: "Chemicals" },
  { symbol: "NOCIL", name: "NOCIL", sector: "Chemicals" },
  { symbol: "LINDEINDIA", name: "Linde India", sector: "Chemicals" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical Industries", sector: "Chemicals" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India", sector: "Chemicals" },
  { symbol: "PIDILITIND", name: "Pidilite Industries", sector: "Chemicals" },
  { symbol: "BASF", name: "BASF India", sector: "Chemicals" },
  { symbol: "NEOGEN", name: "Neogen Chemicals", sector: "Chemicals" },
  { symbol: "TATACHEM", name: "Tata Chemicals", sector: "Chemicals" },
  { symbol: "PCBL", name: "PCBL", sector: "Chemicals" },
  { symbol: "VSBL", name: "Vishnu Shriram Industries", sector: "Chemicals" },
  { symbol: "AARTI", name: "Aarti Drugs", sector: "Chemicals" },
  { symbol: "ROSSARI", name: "Rossari Biotech", sector: "Chemicals" },
  { symbol: "ANUPAM", name: "Anupam Rasayan India", sector: "Chemicals" },
  { symbol: "DHARML", name: "Dharmsi Morarji Chemical", sector: "Chemicals" },
  { symbol: "CAMLIN", name: "Camlin Fine Sciences", sector: "Chemicals" },
  // FMCG & Consumer
  { symbol: "EMAMILTD", name: "Emami", sector: "FMCG" },
  { symbol: "JYOTHYLAB", name: "Jyothy Labs", sector: "FMCG" },
  { symbol: "VSTIND", name: "VST Industries", sector: "FMCG" },
  { symbol: "PATANJALI", name: "Patanjali Foods", sector: "FMCG" },
  { symbol: "GODFRYPHLP", name: "Godfrey Phillips India", sector: "FMCG" },
  { symbol: "CCL", name: "CCL Products India", sector: "FMCG" },
  { symbol: "RADICO", name: "Radico Khaitan", sector: "Consumer" },
  { symbol: "UBL", name: "United Breweries", sector: "Consumer" },
  { symbol: "MCDOWELL-N", name: "United Spirits", sector: "Consumer" },
  { symbol: "VENKEYS", name: "Venky's India", sector: "Consumer" },
  { symbol: "AVANTIFEED", name: "Avanti Feeds", sector: "Consumer" },
  { symbol: "KRBL", name: "KRBL", sector: "Consumer" },
  { symbol: "LT FOODS", name: "LT Foods", sector: "Consumer" },
  { symbol: "LTFOODS", name: "LT Foods", sector: "Consumer" },
  { symbol: "BIKAJI", name: "Bikaji Foods International", sector: "FMCG" },
  { symbol: "PRATAAP", name: "Prataap Snacks", sector: "FMCG" },
  { symbol: "DEVYANI", name: "Devyani International", sector: "Consumer" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods India", sector: "Consumer" },
  { symbol: "JUBLFOOD", name: "Jubilant Foodworks", sector: "Consumer" },
  { symbol: "WESTLIFE", name: "Westlife Foodworld", sector: "Consumer" },
  { symbol: "BARBEQUE", name: "Barbeque Nation Hospitality", sector: "Consumer" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners", sector: "Consumer" },
  { symbol: "THOMASCOOK", name: "Thomas Cook India", sector: "Consumer" },
  { symbol: "MAHINDRAHOLIDAYS", name: "Mahindra Holidays & Resorts", sector: "Consumer" },
  { symbol: "CHALET", name: "Chalet Hotels", sector: "Consumer" },
  { symbol: "LEMON", name: "Lemon Tree Hotels", sector: "Consumer" },
  { symbol: "EIH", name: "EIH (Oberoi Hotels)", sector: "Consumer" },
  { symbol: "TAJGVK", name: "Taj GVK Hotels", sector: "Consumer" },
  { symbol: "WONDERLA", name: "Wonderla Holidays", sector: "Consumer" },
  // Real Estate
  { symbol: "LODHA", name: "Macrotech Developers", sector: "Real Estate" },
  { symbol: "BRIGADE", name: "Brigade Enterprises", sector: "Real Estate" },
  { symbol: "SUNTECK", name: "Sunteck Realty", sector: "Real Estate" },
  { symbol: "SOBHA", name: "Sobha", sector: "Real Estate" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects", sector: "Real Estate" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills", sector: "Real Estate" },
  { symbol: "GODREJPROP", name: "Godrej Properties", sector: "Real Estate" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty", sector: "Real Estate" },
  { symbol: "KOLTEPATIL", name: "Kolte-Patil Developers", sector: "Real Estate" },
  { symbol: "ARVIND", name: "Arvind SmartSpaces", sector: "Real Estate" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace Developers", sector: "Real Estate" },
  { symbol: "SHANKARA", name: "Shankara Building Products", sector: "Real Estate" },
  { symbol: "REALTY", name: "Realty Stocks", sector: "Real Estate" },
  { symbol: "IBREALEST", name: "Indiabulls Real Estate", sector: "Real Estate" },
  { symbol: "NESCO", name: "NESCO", sector: "Real Estate" },
  { symbol: "GANESHHOUSING", name: "Ganesh Housing Corporation", sector: "Real Estate" },
  { symbol: "SIGNATUREG", name: "Signature Global India", sector: "Real Estate" },
  // Metals & Mining
  { symbol: "SAIL", name: "Steel Authority of India", sector: "Metals" },
  { symbol: "HINDZINC", name: "Hindustan Zinc", sector: "Metals" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", sector: "Metals" },
  { symbol: "MOIL", name: "MOIL", sector: "Metals" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes", sector: "Metals" },
  { symbol: "KIOCL", name: "KIOCL", sector: "Metals" },
  { symbol: "NATIONALUM", name: "National Aluminium", sector: "Metals" },
  { symbol: "WELCORP", name: "Welspun Corp", sector: "Metals" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", sector: "Metals" },
  { symbol: "JSPL", name: "Jindal Steel & Power", sector: "Metals" },
  { symbol: "JINDALSAW", name: "Jindal SAW", sector: "Metals" },
  { symbol: "MSTCLTD", name: "MSTC Limited", sector: "Metals" },
  { symbol: "STLTECH", name: "Sterlite Technologies", sector: "Metals" },
  { symbol: "PRAKASH", name: "Prakash Industries", sector: "Metals" },
  { symbol: "GRAVITA", name: "Gravita India", sector: "Metals" },
  { symbol: "VEDL", name: "Vedanta", sector: "Metals" },
  { symbol: "HNDL", name: "Hindalco Industries", sector: "Metals" },
  { symbol: "SHYAMMETL", name: "Shyam Metalics and Energy", sector: "Metals" },
  { symbol: "RKFORGE", name: "Ramkrishna Forgings", sector: "Metals" },
  { symbol: "MAHASTEEL", name: "Maharashtra Seamless", sector: "Metals" },
  { symbol: "PATEL", name: "Patel Integrated Logistics", sector: "Metals" },
  // Energy & Power
  { symbol: "ADANITRANS", name: "Adani Transmission", sector: "Utilities" },
  { symbol: "CESC", name: "CESC", sector: "Utilities" },
  { symbol: "JSWENERGY", name: "JSW Energy", sector: "Utilities" },
  { symbol: "TATAPOWER", name: "Tata Power Company", sector: "Utilities" },
  { symbol: "NHPC", name: "NHPC", sector: "Utilities" },
  { symbol: "SJVN", name: "SJVN", sector: "Utilities" },
  { symbol: "NLCINDIA", name: "NLC India", sector: "Energy" },
  { symbol: "IREDA", name: "Indian Renewable Energy Development Agency", sector: "Utilities" },
  { symbol: "BOMDYEING", name: "Bombay Dyeing & Mfg", sector: "Textiles" },
  { symbol: "SUZLON", name: "Suzlon Energy", sector: "Utilities" },
  { symbol: "INOXWIND", name: "Inox Wind", sector: "Utilities" },
  { symbol: "WINDWORLD", name: "Wind World India", sector: "Utilities" },
  { symbol: "GREENKO", name: "Greenko Energies", sector: "Utilities" },
  { symbol: "ACME", name: "Acme Solar Holdings", sector: "Utilities" },
  { symbol: "PREMIER", name: "Premier Energies", sector: "Utilities" },
  { symbol: "WAAREE", name: "Waaree Energies", sector: "Utilities" },
  { symbol: "WEBSOL", name: "Websol Energy System", sector: "Utilities" },
  { symbol: "BOROSIL", name: "Borosil Renewables", sector: "Utilities" },
  { symbol: "VISAKA", name: "Visaka Industries", sector: "Materials" },
  // Infrastructure & Construction
  { symbol: "KNRCON", name: "KNR Constructions", sector: "Industrials" },
  { symbol: "NCC", name: "NCC", sector: "Industrials" },
  { symbol: "IRB", name: "IRB Infrastructure Developers", sector: "Industrials" },
  { symbol: "ASHOKA", name: "Ashoka Buildcon", sector: "Industrials" },
  { symbol: "PNCINFRA", name: "PNC Infratech", sector: "Industrials" },
  { symbol: "HGINFRA", name: "H.G. Infra Engineering", sector: "Industrials" },
  { symbol: "GRINFRA", name: "G R Infraprojects", sector: "Industrials" },
  { symbol: "RITES", name: "RITES", sector: "Industrials" },
  { symbol: "NBCC", name: "NBCC (India)", sector: "Industrials" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure", sector: "Industrials" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Industrials" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics" },
  { symbol: "SADBHAV", name: "Sadbhav Engineering", sector: "Industrials" },
  { symbol: "DILIPBUILD", name: "Dilip Buildcon", sector: "Industrials" },
  { symbol: "KEC", name: "KEC International", sector: "Industrials" },
  { symbol: "KALPATPOWR", name: "Kalpataru Power Transmission", sector: "Industrials" },
  { symbol: "ENGINERSIN", name: "Engineers India", sector: "Industrials" },
  { symbol: "TEXRAIL", name: "Texmaco Rail & Engineering", sector: "Industrials" },
  { symbol: "TITAGARH", name: "Titagarh Wagons", sector: "Industrials" },
  { symbol: "RAILVIKAS", name: "Rail Vikas Nigam", sector: "Industrials" },
  { symbol: "IRCON", name: "IRCON International", sector: "Industrials" },
  { symbol: "WOCKPHARMA", name: "Wockhardt", sector: "Healthcare" },
  { symbol: "WPIL", name: "WPIL", sector: "Industrials" },
  { symbol: "CAPACITE", name: "Capacit'e Infraprojects", sector: "Industrials" },
  { symbol: "AHLUWALIA", name: "Ahluwalia Contracts", sector: "Industrials" },
  { symbol: "J&KBANK", name: "J&K Bank", sector: "Banking" },
  // Cement & Building Materials
  { symbol: "JKCEMENT", name: "JK Cement", sector: "Materials" },
  { symbol: "RAMCOCEM", name: "The Ramco Cements", sector: "Materials" },
  { symbol: "DALMIA", name: "Dalmia Bharat", sector: "Materials" },
  { symbol: "HEIDELBERG", name: "HeidelbergCement India", sector: "Materials" },
  { symbol: "NUVOCO", name: "Nuvoco Vistas Corporation", sector: "Materials" },
  { symbol: "SANGHI", name: "Sanghi Industries", sector: "Materials" },
  { symbol: "KESORAMIND", name: "Kesoram Industries", sector: "Materials" },
  { symbol: "KAKATCEM", name: "Kakatiya Cement Sugar", sector: "Materials" },
  { symbol: "ASTRAL", name: "Astral", sector: "Materials" },
  { symbol: "SUPREMEIND", name: "Supreme Industries", sector: "Materials" },
  { symbol: "RAIN", name: "Rain Industries", sector: "Materials" },
  { symbol: "JKPAPER", name: "JK Paper", sector: "Materials" },
  { symbol: "TNPL", name: "Tamil Nadu Newsprint", sector: "Materials" },
  { symbol: "NIITLIMITED", name: "NIIT Limited", sector: "IT" },
  { symbol: "HIKAL", name: "Hikal", sector: "Chemicals" },
  { symbol: "BIGBLOC", name: "Bigbloc Construction", sector: "Materials" },
  { symbol: "CENTURY", name: "Century Textiles & Industries", sector: "Materials" },
  // Defence & Aerospace
  { symbol: "BEL", name: "Bharat Electronics", sector: "Defence" },
  { symbol: "HAL", name: "Hindustan Aeronautics", sector: "Defence" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders", sector: "Defence" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders", sector: "Defence" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard", sector: "Defence" },
  { symbol: "BEML", name: "BEML", sector: "Defence" },
  { symbol: "MIDHANI", name: "Mishra Dhatu Nigam", sector: "Defence" },
  { symbol: "PARAS", name: "Paras Defence and Space Technologies", sector: "Defence" },
  { symbol: "IDEAFORGE", name: "IdeaForge Technology", sector: "Defence" },
  { symbol: "DYNAMATECH", name: "Dynamatic Technologies", sector: "Defence" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", sector: "Defence" },
  { symbol: "ASTRA", name: "Astra Microwave Products", sector: "Defence" },
  { symbol: "DATAPATTNS", name: "Data Patterns (India)", sector: "Defence" },
  { symbol: "MTAR", name: "MTAR Technologies", sector: "Defence" },
  { symbol: "SOLARINDS", name: "Solar Industries India", sector: "Defence" },
  // Telecom & Media
  { symbol: "IDEA", name: "Vodafone Idea", sector: "Telecom" },
  { symbol: "MTNL", name: "Mahanagar Telephone Nigam", sector: "Telecom" },
  { symbol: "RAILTEL", name: "RailTel Corporation of India", sector: "Telecom" },
  { symbol: "INDUSTOWER", name: "Indus Towers", sector: "Telecom" },
  { symbol: "VINDHYATEL", name: "Vindhya Telelinks", sector: "Telecom" },
  { symbol: "ZEEL", name: "Zee Entertainment", sector: "Media" },
  { symbol: "NDTV", name: "New Delhi Television", sector: "Media" },
  { symbol: "SUNTV", name: "Sun TV Network", sector: "Media" },
  { symbol: "SAREGAMA", name: "Saregama India", sector: "Media" },
  { symbol: "PVRINOX", name: "PVR Inox", sector: "Media" },
  { symbol: "INOXLEISURE", name: "Inox Leisure", sector: "Media" },
  { symbol: "BALAJITELE", name: "Balaji Telefilms", sector: "Media" },
  { symbol: "NETWORK18", name: "Network18 Media & Investments", sector: "Media" },
  { symbol: "TV18BCAST", name: "TV18 Broadcast", sector: "Media" },
  { symbol: "DISHTV", name: "Dish TV India", sector: "Media" },
  { symbol: "TATASKY", name: "Tata Play (Tata Sky)", sector: "Media" },
  // Logistics
  { symbol: "BLUEDART", name: "Blue Dart Express", sector: "Logistics" },
  { symbol: "DELHIVERY", name: "Delhivery", sector: "Logistics" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics" },
  { symbol: "TCI", name: "Transport Corporation of India", sector: "Logistics" },
  { symbol: "GATI", name: "Gati", sector: "Logistics" },
  { symbol: "MAHLOG", name: "Mahindra Logistics", sector: "Logistics" },
  { symbol: "XPRO", name: "Xpro India", sector: "Logistics" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics", sector: "Logistics" },
  { symbol: "AEGIS", name: "Aegis Logistics", sector: "Logistics" },
  { symbol: "TEAMLEASE", name: "TeamLease Services", sector: "Industrials" },
  { symbol: "QUESS", name: "Quess Corp", sector: "Industrials" },
  // Aviation
  { symbol: "INDIGO", name: "InterGlobe Aviation (IndiGo)", sector: "Aviation" },
  { symbol: "SPICEJET", name: "SpiceJet", sector: "Aviation" },
  { symbol: "AIRINDIA", name: "Air India", sector: "Aviation" },
  // Textiles & Apparel
  { symbol: "TRIDENT", name: "Trident", sector: "Textiles" },
  { symbol: "WELSPUNLIV", name: "Welspun Living", sector: "Textiles" },
  { symbol: "PAGEIND", name: "Page Industries", sector: "Consumer" },
  { symbol: "ARVIND", name: "Arvind", sector: "Textiles" },
  { symbol: "RUPA", name: "Rupa & Company", sector: "Textiles" },
  { symbol: "DOLLAR", name: "Dollar Industries", sector: "Textiles" },
  { symbol: "LAXMIMACH", name: "Lakshmi Machine Works", sector: "Textiles" },
  { symbol: "RAYMOND", name: "Raymond", sector: "Textiles" },
  { symbol: "MAFATLAL", name: "Mafatlal Industries", sector: "Textiles" },
  { symbol: "SUTLEJ", name: "Sutlej Textiles and Industries", sector: "Textiles" },
  { symbol: "VARDHMAN", name: "Vardhman Textiles", sector: "Textiles" },
  { symbol: "SPENTEX", name: "Spentex Industries", sector: "Textiles" },
  { symbol: "GARWARE", name: "Garware Technical Fibres", sector: "Textiles" },
  // Sugar
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills", sector: "Consumer" },
  { symbol: "DWARIKESH", name: "Dwarikesh Sugar Industries", sector: "Consumer" },
  { symbol: "EIDPARRY", name: "EID Parry India", sector: "Consumer" },
  { symbol: "TRIVENI", name: "Triveni Engineering & Industries", sector: "Consumer" },
  { symbol: "SHREERENUKA", name: "Shree Renuka Sugars", sector: "Consumer" },
  { symbol: "MAWANA", name: "Mawana Sugars", sector: "Consumer" },
  { symbol: "BAJAJHIND", name: "Bajaj Hindusthan Sugar", sector: "Consumer" },
  // Agri & Fertilisers
  { symbol: "COROMANDEL", name: "Coromandel International", sector: "Chemicals" },
  { symbol: "DEEPAK", name: "Deepak Fertilisers & Petrochemicals", sector: "Chemicals" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley Fertilizers", sector: "Chemicals" },
  { symbol: "FACT", name: "Fertilisers and Chemicals Travancore", sector: "Chemicals" },
  { symbol: "KSCL", name: "Kaveri Seed Company", sector: "Chemicals" },
  { symbol: "RALLIS", name: "Rallis India", sector: "Chemicals" },
  { symbol: "DHANUKA", name: "Dhanuka Agritech", sector: "Chemicals" },
  { symbol: "BAYER", name: "Bayer CropScience", sector: "Chemicals" },
  { symbol: "INSECTICID", name: "Insecticides India", sector: "Chemicals" },
  // Consumer Electronics & Electricals
  { symbol: "DIXON", name: "Dixon Technologies", sector: "Consumer" },
  { symbol: "AMBER", name: "Amber Enterprises India", sector: "Consumer" },
  { symbol: "BLUESTAR", name: "Blue Star", sector: "Consumer" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India", sector: "Consumer" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer Electricals", sector: "Consumer" },
  { symbol: "HAVELLS", name: "Havells India", sector: "Consumer" },
  { symbol: "KEI", name: "KEI Industries", sector: "Consumer" },
  { symbol: "POLYCAB", name: "Polycab India", sector: "Consumer" },
  { symbol: "FINOLEX", name: "Finolex Cables", sector: "Consumer" },
  { symbol: "VGUARD", name: "V-Guard Industries", sector: "Consumer" },
  { symbol: "ORIENTELEC", name: "Orient Electric", sector: "Consumer" },
  { symbol: "BAJAJELE", name: "Bajaj Electricals", sector: "Consumer" },
  { symbol: "SYSFIN", name: "Systemantics India", sector: "Consumer" },
  { symbol: "KAYNES", name: "Kaynes Technology India", sector: "Consumer" },
  { symbol: "SYRMA", name: "Syrma SGS Technology", sector: "Consumer" },
  // Retail
  { symbol: "DMART", name: "Avenue Supermarts (D-Mart)", sector: "Consumer" },
  { symbol: "VMART", name: "V-Mart Retail", sector: "Consumer" },
  { symbol: "TRENT", name: "Trent", sector: "Consumer" },
  { symbol: "SHOPERSTOP", name: "Shoppers Stop", sector: "Consumer" },
  { symbol: "ABRLOFSN", name: "Aditya Birla Fashion & Retail", sector: "Consumer" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion and Retail", sector: "Consumer" },
  { symbol: "BATAINDIA", name: "Bata India", sector: "Consumer" },
  { symbol: "RELAXO", name: "Relaxo Footwears", sector: "Consumer" },
  { symbol: "METRO", name: "Metro Brands", sector: "Consumer" },
  { symbol: "CAMPUS", name: "Campus Activewear", sector: "Consumer" },
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer" },
  { symbol: "KALYAN", name: "Kalyan Jewellers India", sector: "Consumer" },
  { symbol: "SENCO", name: "Senco Gold", sector: "Consumer" },
  { symbol: "THANGAMAYL", name: "Thangamayil Jewellery", sector: "Consumer" },
  { symbol: "PCJEWELLER", name: "PC Jeweller", sector: "Consumer" },
  { symbol: "VAIBHAVGBL", name: "Vaibhav Global", sector: "Consumer" },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports", sector: "Consumer" },
  { symbol: "MANYAVAR", name: "Vedant Fashions (Manyavar)", sector: "Consumer" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures", sector: "Consumer" },
  // Paint & Coatings
  { symbol: "ASIANPAINT", name: "Asian Paints", sector: "Materials" },
  { symbol: "BERGEPAINT", name: "Berger Paints India", sector: "Materials" },
  { symbol: "KANSAINER", name: "Kansai Nerolac Paints", sector: "Materials" },
  { symbol: "AKZOINDIA", name: "Akzo Nobel India", sector: "Materials" },
  { symbol: "INDIGO-PAINTS", name: "Indigo Paints", sector: "Materials" },
  { symbol: "INDIGOPNTS", name: "Indigo Paints", sector: "Materials" },
  // New Age / Fintech
  { symbol: "ZOMATO", name: "Zomato", sector: "Consumer" },
  { symbol: "PAYTM", name: "One 97 Communications", sector: "Finance" },
  { symbol: "POLICYBZR", name: "PB Fintech", sector: "Finance" },
  { symbol: "CARTRADE", name: "CarTrade Tech", sector: "Consumer" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", sector: "IT" },
  { symbol: "NAUKRI", name: "Info Edge India", sector: "IT" },
  { symbol: "JUSTDIAL", name: "Just Dial", sector: "IT" },
  { symbol: "MAPMYINDIA", name: "C.E. Info Systems (MapmyIndia)", sector: "IT" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics", sector: "IT" },
  { symbol: "AZAD", name: "Azad Engineering", sector: "Industrials" },
  { symbol: "SWIGGY", name: "Bundl Technologies (Swiggy)", sector: "Consumer" },
  { symbol: "HYUNDAI", name: "Hyundai Motor India", sector: "Auto" },
  { symbol: "OLA", name: "Ola Electric Mobility", sector: "Auto" },
  // Industrials & Capital Goods
  { symbol: "ABB", name: "ABB India", sector: "Industrials" },
  { symbol: "SIEMENS", name: "Siemens India", sector: "Industrials" },
  { symbol: "CUMMINSIND", name: "Cummins India", sector: "Industrials" },
  { symbol: "THERMAX", name: "Thermax", sector: "Industrials" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", sector: "Industrials" },
  { symbol: "GMMPFAUDLR", name: "GMM Pfaudler", sector: "Industrials" },
  { symbol: "ELGIEQUIP", name: "Elgi Equipments", sector: "Industrials" },
  { symbol: "GRINDWELL", name: "Grindwell Norton", sector: "Industrials" },
  { symbol: "TIMKEN", name: "Timken India", sector: "Industrials" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India", sector: "Auto" },
  { symbol: "SKF", name: "SKF India", sector: "Industrials" },
  { symbol: "NTN", name: "NTN Bearing-Rings", sector: "Industrials" },
  { symbol: "GREAVES", name: "Greaves Cotton", sector: "Industrials" },
  { symbol: "MHRIL", name: "Mahindra Holidays & Resorts", sector: "Consumer" },
  { symbol: "CARBORUNIV", name: "Carborundum Universal", sector: "Industrials" },
  { symbol: "INGERRAND", name: "Ingersoll Rand India", sector: "Industrials" },
  { symbol: "PRAJ", name: "Praj Industries", sector: "Industrials" },
  { symbol: "ISGEC", name: "Isgec Heavy Engineering", sector: "Industrials" },
  { symbol: "VOLTAMP", name: "Voltamp Transformers", sector: "Industrials" },
  { symbol: "APAR", name: "Apar Industries", sector: "Industrials" },
  { symbol: "TEXMOPIPES", name: "Texmo Pipes and Products", sector: "Industrials" },
  // Miscellaneous BSE Additional
  { symbol: "IREDA", name: "Indian Renewable Energy Dev Agency", sector: "Utilities" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", sector: "Industrials" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corp", sector: "Finance" },
  { symbol: "PSUBNK", name: "PSU Banks", sector: "Banking" },
  { symbol: "ZYDUSWELL", name: "Zydus Wellness", sector: "FMCG" },
  { symbol: "HATSUN", name: "Hatsun Agro Product", sector: "FMCG" },
  { symbol: "HERITAGE", name: "Heritage Foods", sector: "FMCG" },
  { symbol: "PARAG", name: "Parag Milk Foods", sector: "FMCG" },
  { symbol: "AGROPHOS", name: "Agro Phos India", sector: "Chemicals" },
  { symbol: "NESLIND", name: "Nestle India", sector: "FMCG" },
  { symbol: "SHAREINDIA", name: "Share India Securities", sector: "Finance" },
  { symbol: "FIVESTAR", name: "Five-Star Business Finance", sector: "Finance" },
  { symbol: "SBFC", name: "SBFC Finance", sector: "Finance" },
  { symbol: "POONAWALLA", name: "Poonawalla Fincorp", sector: "Finance" },
  { symbol: "NUVAMA", name: "Nuvama Wealth Management", sector: "Finance" },
  { symbol: "GEOJIT", name: "Geojit Financial Services", sector: "Finance" },
  { symbol: "EDELWEISS", name: "Edelweiss Financial Services", sector: "Finance" },
  { symbol: "JM", name: "JM Financial", sector: "Finance" },
  { symbol: "JMFINANCIL", name: "JM Financial", sector: "Finance" },
  { symbol: "RELIGARE", name: "Religare Enterprises", sector: "Finance" },
  // Conglomerates
  { symbol: "TATAPOWER", name: "Tata Power Company", sector: "Utilities" },
  { symbol: "TATACHEM", name: "Tata Chemicals", sector: "Chemicals" },
  { symbol: "TATAMETALI", name: "Tata Metaliks", sector: "Metals" },
  { symbol: "TATACOMM", name: "Tata Communications", sector: "Telecom" },
  { symbol: "VOLTAS", name: "Voltas", sector: "Consumer" },
  { symbol: "TINPLATE", name: "The Tinplate Company of India", sector: "Metals" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", sector: "IT" },
  { symbol: "TATAINVEST", name: "Tata Investment Corporation", sector: "Finance" },
  { symbol: "TATAMTRDVR", name: "Tata Motors DVR", sector: "Auto" },
  { symbol: "ADANIENT", name: "Adani Enterprises", sector: "Industrials" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", sector: "Utilities" },
  { symbol: "ADANIPOWER", name: "Adani Power", sector: "Utilities" },
  { symbol: "ADANITRANS", name: "Adani Transmission", sector: "Utilities" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Industrials" },
  { symbol: "ADANIWILMAR", name: "Adani Wilmar", sector: "FMCG" },
  { symbol: "AWL", name: "Adani Wilmar", sector: "FMCG" },
  // More Banking/PSU
  { symbol: "MAHABANK", name: "Bank of Maharashtra", sector: "Banking" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking" },
  { symbol: "BANKINDIA", name: "Bank of India", sector: "Banking" },
  { symbol: "UCOBANK", name: "UCO Bank", sector: "Banking" },
  { symbol: "CENTRALBK", name: "Central Bank of India", sector: "Banking" },
  { symbol: "INDIANB", name: "Indian Bank", sector: "Banking" },
  { symbol: "IOB", name: "Indian Overseas Bank", sector: "Banking" },
  { symbol: "ANDHRABANK", name: "Andhra Bank", sector: "Banking" },
  { symbol: "DENABANK", name: "Dena Bank", sector: "Banking" },
  { symbol: "SYNDIBANK", name: "Syndicate Bank", sector: "Banking" },
  // More IT
  { symbol: "FIRSTSOURCE", name: "Firstsource Solutions", sector: "IT" },
  { symbol: "SUBEX", name: "Subex", sector: "IT" },
  { symbol: "NUCLEUS", name: "Nucleus Software Exports", sector: "IT" },
  { symbol: "MOSCHIP", name: "MosChip Technologies", sector: "IT" },
  { symbol: "SASKEN", name: "Sasken Technologies", sector: "IT" },
  { symbol: "ZENSAR", name: "Zensar Technologies", sector: "IT" },
  { symbol: "HEXAWARE", name: "Hexaware Technologies", sector: "IT" },
  { symbol: "LTIM", name: "LTIMindtree", sector: "IT" },
  { symbol: "RAMCOIND", name: "Ramco Industries", sector: "IT" },
  { symbol: "RAMCOSYS", name: "Ramco Systems", sector: "IT" },
  { symbol: "TATAELXSI", name: "Tata Elxsi", sector: "IT" },
  { symbol: "3IINFOTECH", name: "3i Infotech", sector: "IT" },
  { symbol: "SAKSOFT", name: "Saksoft", sector: "IT" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", sector: "IT" },
  { symbol: "XCHANGING", name: "Xchanging Solutions", sector: "IT" },
  { symbol: "SAKSOFT", name: "Saksoft", sector: "IT" },
  // Oil & Gas
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corp", sector: "Energy" },
  { symbol: "BPCL", name: "Bharat Petroleum", sector: "Energy" },
  { symbol: "IOC", name: "Indian Oil Corporation", sector: "Energy" },
  { symbol: "GAIL", name: "GAIL (India)", sector: "Energy" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Energy" },
  { symbol: "OIL", name: "Oil India", sector: "Energy" },
  { symbol: "PETRONET", name: "Petronet LNG", sector: "Energy" },
  { symbol: "GSPL", name: "Gujarat State Petronet", sector: "Energy" },
  { symbol: "IGL", name: "Indraprastha Gas", sector: "Energy" },
  { symbol: "MGL", name: "Mahanagar Gas", sector: "Energy" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas", sector: "Energy" },
  { symbol: "ATGL", name: "Adani Total Gas", sector: "Energy" },
  // Gems & Jewellery
  { symbol: "TITAN", name: "Titan Company", sector: "Consumer" },
  { symbol: "KALYAN", name: "Kalyan Jewellers India", sector: "Consumer" },
  { symbol: "RAJESHEXPO", name: "Rajesh Exports", sector: "Consumer" },
  { symbol: "MSTC", name: "MSTC Limited", sector: "Metals" },
  // Hospitality & Travel
  { symbol: "INDHOTEL", name: "Indian Hotels", sector: "Consumer" },
  { symbol: "EIH", name: "EIH (Oberoi Hotels)", sector: "Consumer" },
  { symbol: "TAJGVK", name: "Taj GVK Hotels", sector: "Consumer" },
  { symbol: "CHALET", name: "Chalet Hotels", sector: "Consumer" },
  { symbol: "LEMON", name: "Lemon Tree Hotels", sector: "Consumer" },
  { symbol: "MAHINDRAHOLIDAYS", name: "Mahindra Holidays & Resorts", sector: "Consumer" },
  { symbol: "WONDERLA", name: "Wonderla Holidays", sector: "Consumer" },
  { symbol: "IRCTC", name: "Indian Railway Catering", sector: "Consumer" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners", sector: "Consumer" },
  { symbol: "THOMASCOOK", name: "Thomas Cook India", sector: "Consumer" },
  // Paper & Packaging
  { symbol: "JKPAPER", name: "JK Paper", sector: "Materials" },
  { symbol: "TNPL", name: "Tamil Nadu Newsprint", sector: "Materials" },
  { symbol: "WESTERNINDIA", name: "Western India Plywood", sector: "Materials" },
  { symbol: "ANDHRPAPER", name: "Andhra Paper", sector: "Materials" },
  { symbol: "STARPAPERS", name: "Star Paper Mills", sector: "Materials" },
  { symbol: "UFLEX", name: "Uflex", sector: "Materials" },
  { symbol: "COSMO", name: "Cosmo Films", sector: "Materials" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", sector: "Metals" },
  { symbol: "EPL", name: "EPL (Essel Propack)", sector: "Materials" },
  { symbol: "MOLD-TEK", name: "Mold-Tek Packaging", sector: "Materials" },
  // Specialty Finance
  { symbol: "BAJFINANCE", name: "Bajaj Finance", sector: "Finance" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv", sector: "Finance" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance", sector: "Finance" },
  { symbol: "L&TFH", name: "L&T Finance Holdings", sector: "Finance" },
  { symbol: "LTFH", name: "L&T Finance Holdings", sector: "Finance" },
  { symbol: "MAHFIN", name: "Mahindra Finance", sector: "Finance" },
  { symbol: "M&MFIN", name: "Mahindra & Mahindra Financial", sector: "Finance" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance", sector: "Finance" },
  { symbol: "SCUF", name: "Shriram City Union Finance", sector: "Finance" },
  { symbol: "MUTHOOTCAP", name: "Muthoot Capital Services", sector: "Finance" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance", sector: "Finance" },
  { symbol: "IIFLWAM", name: "IIFL Wealth Management", sector: "Finance" },
  { symbol: "WEALTHMGT", name: "360 One WAM", sector: "Finance" },
  { symbol: "ANMI", name: "ANMI Financial Services", sector: "Finance" },
  // More small/mid caps popular in trading
  { symbol: "MPHASIS", name: "Mphasis", sector: "IT" },
  { symbol: "PERSISTENT", name: "Persistent Systems", sector: "IT" },
  { symbol: "KPITTECH", name: "KPIT Technologies", sector: "IT" },
  { symbol: "TATATECH", name: "Tata Technologies", sector: "IT" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT" },
  { symbol: "NEWGEN", name: "Newgen Software Technologies", sector: "IT" },
  { symbol: "INTELLECT", name: "Intellect Design Arena", sector: "IT" },
  { symbol: "CYIENT", name: "Cyient", sector: "IT" },
  { symbol: "BIRLASOFT", name: "Birlasoft", sector: "IT" },
  { symbol: "ECLERX", name: "eClerx Services", sector: "IT" },
  { symbol: "SONATSOFTW", name: "Sonata Software", sector: "IT" },
  { symbol: "MASTEK", name: "Mastek", sector: "IT" },
  { symbol: "FSL", name: "Firstsource Solutions", sector: "IT" },
  { symbol: "TANLA", name: "Tanla Platforms", sector: "IT" },
  { symbol: "ROUTE", name: "Route Mobile", sector: "IT" },
  { symbol: "RATEGAIN", name: "RateGain Travel Technologies", sector: "IT" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics", sector: "IT" },
  { symbol: "MAPMYINDIA", name: "MapmyIndia", sector: "IT" },
  { symbol: "TTML", name: "Tata Teleservices Maharashtra", sector: "Telecom" },
  { symbol: "STFC", name: "Shriram Transport Finance", sector: "Finance" },
  // Tires
  { symbol: "BALKRISIND", name: "Balkrishna Industries", sector: "Auto" },
  { symbol: "CEATLTD", name: "CEAT", sector: "Auto" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres", sector: "Auto" },
  { symbol: "MRF", name: "MRF", sector: "Auto" },
  { symbol: "GOODYEAR", name: "Goodyear India", sector: "Auto" },
  { symbol: "TVSSRICHAK", name: "TVS Srichakra", sector: "Auto" },
  { symbol: "FALCONTYRES", name: "Falcon Tyres", sector: "Auto" },
  // Glass & Ceramics
  { symbol: "BOROSIL", name: "Borosil Renewables", sector: "Materials" },
  { symbol: "HNGIL", name: "Hindustan National Glass", sector: "Materials" },
  { symbol: "ORIENTCEM", name: "Orient Cement", sector: "Materials" },
  { symbol: "KAJARIA", name: "Kajaria Ceramics", sector: "Materials" },
  { symbol: "SOMANYCER", name: "Somany Ceramics", sector: "Materials" },
  { symbol: "CERA", name: "Cera Sanitaryware", sector: "Materials" },
  { symbol: "HSIL", name: "HSIL", sector: "Materials" },
  // More PSU
  { symbol: "HAL", name: "Hindustan Aeronautics", sector: "Defence" },
  { symbol: "BEL", name: "Bharat Electronics", sector: "Defence" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", sector: "Industrials" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics" },
  { symbol: "NMDC", name: "NMDC", sector: "Metals" },
  { symbol: "MOIL", name: "MOIL", sector: "Metals" },
  { symbol: "KIOCL", name: "KIOCL", sector: "Metals" },
  { symbol: "NATIONALUM", name: "National Aluminium", sector: "Metals" },
  { symbol: "SAIL", name: "Steel Authority of India", sector: "Metals" },
  { symbol: "COALINDIA", name: "Coal India", sector: "Energy" },
  { symbol: "NLCINDIA", name: "NLC India", sector: "Energy" },
  { symbol: "OIL", name: "Oil India", sector: "Energy" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation", sector: "Energy" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation", sector: "Energy" },
  { symbol: "IOC", name: "Indian Oil Corporation", sector: "Energy" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corp", sector: "Energy" },
  { symbol: "EIL", name: "Engineers India", sector: "Industrials" },
  { symbol: "IRCON", name: "IRCON International", sector: "Industrials" },
  { symbol: "RVNL", name: "Rail Vikas Nigam", sector: "Industrials" },
  { symbol: "RAILVIKAS", name: "Rail Vikas Nigam", sector: "Industrials" },
  { symbol: "RITES", name: "RITES", sector: "Industrials" },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation", sector: "Finance" },
  { symbol: "REC", name: "REC Limited", sector: "Finance" },
  { symbol: "PFC", name: "Power Finance Corporation", sector: "Finance" },
  { symbol: "NHPC", name: "NHPC", sector: "Utilities" },
  { symbol: "SJVN", name: "SJVN", sector: "Utilities" },
  { symbol: "NTPC", name: "NTPC Limited", sector: "Utilities" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Utilities" },
  { symbol: "IREDA", name: "Indian Renewable Energy Dev Agency", sector: "Utilities" },
  { symbol: "HUDCO", name: "Housing & Urban Development Corp", sector: "Finance" },
  { symbol: "NBCC", name: "NBCC (India)", sector: "Industrials" },
];

export function searchNseStocks(query: string, limit = 8): NseStock[] {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase();
  return NSE_STOCKS.filter(
    (s) =>
      s.symbol.startsWith(q) ||
      s.name.toUpperCase().includes(q) ||
      s.sector.toUpperCase().includes(q)
  ).slice(0, limit);
}
